# Metadata, every api definition must include the version of the OpenAPI specification
openapi: 3.0.4
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
#  server templating
  - url: https://{customerId}.saas-app.com:{port}/v2
    variables:
      customerId:
        default: demo
        description: Customer ID assigned by the service provider
      port:
        enum:
          - '443'
          - '8443'
        default: '443'

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
          # media type: can use standard media types and vendor-specific media types(like .vnd)
          ### standard media types
          # application/json
          # application/xml
          # application/x-www-form-urlencoded
          # multipart/form-data
          # text/plain; charset=utf-8
          # text/html
          # application/pdf
          # image/png
          ### vendor-specific media types
          # application/vnd.mycompany.myapp.v2+json
          # application/vnd.ms-excel
          # application/vnd.openstreetmap.data+xml
          # application/vnd.github-issue.text+json
          # application/vnd.github.v3.diff
          # image/vnd.djvu
            application/json:
              schema:
                type: array
                items:
                  type: string

  /employees:
    get:
      responses:
        "200": # Response
          description: OK
          content: # Response body
            application/json: # Media type
              schema:
                $ref: "#/components/schemas/Employee" # Reference to object definition
            application/xml: # Media type
              schema:
                $ref: "#/components/schemas/Employee" # Reference to object definition
                
components:
  schemas:
    Employee: # Object definition
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        fullTime:
          type: boolean